### ISSUE TITLE
Display Service Type In Inventory Stock

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#10]
![image](https://user-images.githubusercontent.com/45279206/85506072-48c63200-b60d-11ea-83fa-ab1c21b46838.png)

https://live.membroz.com/#/pages/dynamic-forms/form/5ae982ec8f533b1d0cff9875

salonmembroz@gmail.com

**Comment by hirenmistry17** [comment]
Inventory stock can't added from here,
need to create purchase request to head branch 

and remove permission this button (Add Inventory Stock ) from dynamic list
