### ISSUE TITLE
When We Click On Check Out Butoon After Check Out Page Look LIke This remaining Appointment Not Display

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#114]
![image](https://user-images.githubusercontent.com/45279206/87301629-8e4f8e00-c52d-11ea-9cdc-f9eb39778b23.png)

![image](https://user-images.githubusercontent.com/45279206/87301642-94de0580-c52d-11ea-9357-9b04b29ad692.png)

https://live.membroz.com/#/pages/appointment-module/frontdesk2

gymmembroz@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21 Fixed. pls check on next release
