### ISSUE TITLE
Remove Background Image

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#125]
![image](https://user-images.githubusercontent.com/45279206/87748091-9bf96200-c812-11ea-9aa8-4455e1ae2bbc.png)

http://enterprise.membroz.com/#/pages/appointment-module/frontdesk2

branch2@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21 fixed. pls check on next release
