### ISSUE TITLE
Deleted Service Display

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#129]
![image](https://user-images.githubusercontent.com/45279206/87779675-cf57e300-c84a-11ea-8fed-42c67a14b52b.png)

http://enterprise.membroz.com/#/pages/appointment-module/frontdesk2

branch2@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21 fixed. you can see changes on next release
