### ISSUE TITLE
Appointment Not Display Properly In Frontdesk

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#134]
![image](https://user-images.githubusercontent.com/45279206/88010957-bfcee780-cb33-11ea-9db6-08fd569d349f.png)

![image](https://user-images.githubusercontent.com/45279206/88010986-cd846d00-cb33-11ea-8d33-2f7b37219f30.png)

http://enterprise.membroz.com/#/pages/appointment-module/frontdesk2

branch2@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21 : you can see that timeslot is blank. why timeslot is blank ? can you please explain the step which you have done. so I can investigate 

without timeslot, it can not appear in front desk

**Comment by fazalkhalifa21** [comment]
Ok I Got It
