### ISSUE TITLE
Value Could Be Decreased Only One

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#17]
![image](https://user-images.githubusercontent.com/45279206/85691770-6caf7380-b6f2-11ea-84b8-a59dc47cc049.png)

Enterprise Membroz
CLINI10002

**Comment by hirenmistry17** [comment]
Issue fixed,
related to : https://github.com/jariwbh/Membroz-QA/issues/101

**Comment by fazalkhalifa21** [comment]
Is It Fixed On Enterprise App BCZ This Issue Is For Enterprise App
