### ISSUE TITLE
Mark It As Mandatory

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#20]
![image](https://user-images.githubusercontent.com/45279206/85714078-b191d500-b707-11ea-8780-1815c87c2bb8.png)

https://live.membroz.com/#/pages/dynamic-forms/form/599673a925f548d7dbbd7c86

gymmembroz@gmail.com

**Comment by jariwbh** [comment]
Actually I removed that mandatory.. if you want to add any extra field, use same user id Setup > Member field

**Comment by fazalkhalifa21** [comment]
Ok I Will Try
