### ISSUE TITLE
Appointment Not Display In FrontDesk Calender

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#23]
![image](https://user-images.githubusercontent.com/45279206/85820081-1d6d4f80-b793-11ea-9a01-f56c77ce501e.png)

http://enterprise.membroz.com/#/pages/appointment-module/frontdesk2

branch2@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21 I have added time validation on add / edit service page.
