### ISSUE TITLE
Package Amount Will Not Display In Live.Membroz Mobile App

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#35]
![image](https://user-images.githubusercontent.com/45279206/85852289-e700f600-b7cd-11ea-9e37-5420117db84a.png)

**Comment by jariwbh** [comment]
Please update package amount from package edit form.
![image](https://user-images.githubusercontent.com/1841956/85854525-2b8e9080-b7d2-11ea-884a-d24d2665553f.png)
