### ISSUE TITLE
Display Wrong Data In MemberShip Summary Report

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#36]
![image](https://user-images.githubusercontent.com/45279206/85853704-9dfe7100-b7d0-11ea-8f48-b208204778f4.png)

http://enterprise.membroz.com/#/pages/dynamic-bireport/bireport-detail/5def9275bda0fa628246216c
branch2@gmail.com

**Comment by jariwbh** [comment]
Fixed.. check - http://enterprise.membroz.com/#/pages/dynamic-bireport/bireport-detail/5ef6005afdfdd56ebcfd2892
![image](https://user-images.githubusercontent.com/1841956/85917945-36056480-b87c-11ea-84bc-f9a1277e5885.png)
