### ISSUE TITLE
Display Only Membership Name In Membership Payment Term Summary Report

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#37]
![image](https://user-images.githubusercontent.com/45279206/85854923-f6cf0900-b7d2-11ea-9cbe-77f896ace294.png)

http://enterprise.membroz.com/#/pages/dynamic-bireport/bireport-detail/5c4ac7606561a89a9e409e97

branch2@gmail.com

**Comment by jariwbh** [comment]
fixed
![image](https://user-images.githubusercontent.com/1841956/85917984-79f86980-b87c-11ea-8c4d-5ed70abe7cd1.png)
