### ISSUE TITLE
Display Validation Failed But ON Which Line It Will Not Display

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#71]
![image](https://user-images.githubusercontent.com/45279206/86348668-97af3f80-bc7d-11ea-8cd0-ce13176628ca.png)

https://live.membroz.com/#/pages/wallet/settings

salonmembroz@gmail.com

**Comment by jariwbh** [comment]
![image](https://user-images.githubusercontent.com/1841956/87427417-5bc19600-c5fe-11ea-8197-52bc071dc83f.png)
