### ISSUE TITLE
Hotels Not Display Properly

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#77]
![image](https://user-images.githubusercontent.com/45279206/86453464-72810680-bd3b-11ea-81af-79501cd9971c.png)

![image](https://user-images.githubusercontent.com/45279206/86453473-7745ba80-bd3b-11ea-8b68-ec79ab987dde.png)

PARKRIVIERA10001

**Comment by AvaniGhervara** [comment]
issue solved please test in next build
