### ISSUE TITLE
Location Not Display

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#78]
![image](https://user-images.githubusercontent.com/45279206/86454076-5e89d480-bd3c-11ea-89a6-9af8bad37d77.png)

![image](https://user-images.githubusercontent.com/45279206/86464860-0f4c9f80-bd4e-11ea-9f4d-80262c9bd596.png)

PARKRIVIERA10001

**Comment by hirenmistry17** [comment]
This are enhancement, 
The tabs "about us" and "amenities" are complete and "rooms" and "Location" are incomplete
