### ISSUE TITLE
Diet Not Display In Mobile App

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#81]
![image](https://user-images.githubusercontent.com/45279206/86559110-ca588100-bf78-11ea-88c6-e39e55dd9a7e.png)

![image](https://user-images.githubusercontent.com/45279206/86559191-02f85a80-bf79-11ea-9e7a-e2088bd51f7d.png)

ALLIN-182-10001

**Comment by AvaniGhervara** [comment]
issue fixed please test in next build
