### ISSUE TITLE
Display Different Data

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#82]
![image](https://user-images.githubusercontent.com/45279206/86578501-89249900-bf99-11ea-8eb2-23d286908e4d.png)

![image](https://user-images.githubusercontent.com/45279206/86578674-ce48cb00-bf99-11ea-9ee1-064d9ecdbd9a.png)

ALLIN-182-10001

**Comment by jariwbh** [comment]
Please recheck, you can fix permission if you see such issue.
