### ISSUE TITLE
Configured Button Not Working

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#93]
![image](https://user-images.githubusercontent.com/45279206/86774187-edb42680-c073-11ea-952e-bc50445993f6.png)

https://live.membroz.com/#/pages/integration/lists

gymmembroz@gmail.com

**Comment by samarthkrtya** [comment]
@fazalkhalifa21  Fixed. 
payu and easebuzs forms are not there in forms collection. i have added payu and easebuzz form document. please check.
