### ISSUE TITLE
Please Check The Image For Understanding The Bug

### ISSUE THREAD

**Issue by fazalkhalifa21** [jariwbh/Membroz-QA#96]
![image](https://user-images.githubusercontent.com/45279206/86997205-29adcf80-c1cb-11ea-94ad-a6ab5ad183b4.png)

![image](https://user-images.githubusercontent.com/45279206/86997291-5cf05e80-c1cb-11ea-8be2-7cef540c4ebc.png)

![image](https://user-images.githubusercontent.com/45279206/86997334-6bd71100-c1cb-11ea-9d17-b0df71766591.png)

When We Cancel Above Page It Will Create New Batch

![image](https://user-images.githubusercontent.com/45279206/86997401-945f0b00-c1cb-11ea-981a-a5671ff5c8c8.png)

https://live.membroz.com/#/pages/dynamic-list/list/classroom

gymmembroz@gmail.com

**Comment by prashantkrtya** [comment]
Popup button Label is updated to Clone from Delete, & other functionality is ok , according to button Function.
